# Generated by Django 3.0 on 2020-10-02 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date saved'),
        ),
        migrations.AddField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
