# Generated by Django 3.0 on 2020-10-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
