# Generated by Django 3.0 on 2020-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='illustration',
            field=models.ImageField(null=True, upload_to='static/images/illustration', verbose_name='picture'),
        ),
    ]
