# Generated by Django 3.0 on 2020-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0009_auto_20201102_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.CharField(max_length=100),
        ),
    ]
