# Generated by Django 3.0 on 2020-11-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0013_auto_20201102_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='illustration',
        ),
    ]
