# Generated by Django 3.1.1 on 2020-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0014_remove_article_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ref',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
